# Generated by Django 2.2 on 2020-01-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotableQuotesApp', '0002_qoutes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='qoutes',
            name='qouter',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
