# Generated by Django 2.2 on 2020-01-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotableQuotesApp', '0003_qoutes_qouter'),
    ]

    operations = [
        migrations.AddField(
            model_name='qoutes',
            name='isPosted',
            field=models.BooleanField(default=False),
        ),
    ]
