# Generated by Django 2.2 on 2020-01-13 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotableQuotesApp', '0004_qoutes_isposted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qoutes',
            new_name='Quotes',
        ),
        migrations.RenameField(
            model_name='quotes',
            old_name='qouter',
            new_name='quoter',
        ),
    ]
